// ─── Flashcard Seed Data ──────────────────────────────────────────────────────
// 150 flashcards across 5 decks for TWU Dallas BSN Semester 5
// ──────────────────────────────────────────────────────────────────────────────

export interface FlashcardDeck {
  id: string;
  name: string;
  description: string;
  course_code: string;
  card_count: number;
}

export interface Flashcard {
  id: string;
  deck_id: string;
  front: string;
  back: string;
  hint?: string;
  course_code: string;
  topic: string;
  difficulty: 1 | 2 | 3;
}

export const decks: FlashcardDeck[] = [
  {
    id: 'deck-pharm',
    name: 'Pharmacology Core',
    description: 'Drug classes, MOA, hold parameters, lab monitoring, and high-alert flags for NURS 3813.',
    course_code: 'NURS 3813',
    card_count: 40,
  },
  {
    id: 'deck-assess',
    name: 'Health Assessment',
    description: 'Assessment techniques, normal vs abnormal findings, lung/heart/bowel sounds for NURS 3153.',
    course_code: 'NURS 3153',
    card_count: 30,
  },
  {
    id: 'deck-foundations',
    name: 'Foundations of Nursing',
    description: 'ADPIE, QSEN, infection control, safety, Maslow, legal/ethical concepts for NURS 3193.',
    course_code: 'NURS 3193',
    card_count: 30,
  },
  {
    id: 'deck-patho',
    name: 'Pathophysiology',
    description: 'HF, COPD, DM, pneumonia, UTI, sepsis, HTN, renal failure, stroke for BIOL 4344.',
    course_code: 'BIOL 4344',
    card_count: 30,
  },
  {
    id: 'deck-nclex',
    name: 'NCLEX Priority Setting',
    description: 'ABCs, Maslow, "which patient first" scenarios, delegation rules, safety vs comfort.',
    course_code: 'NURS 3193',
    card_count: 20,
  },
];

export const flashcards: Flashcard[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // DECK 1 — NURS 3813 Pharmacology Core (40 cards)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'fc-p01',
    deck_id: 'deck-pharm',
    front: 'What drug class ends in "-olol"?',
    back: 'Beta-blockers (e.g., metoprolol, atenolol, carvedilol). They reduce heart rate and blood pressure by blocking beta-adrenergic receptors.',
    hint: 'Think "LOL" = Low Output, Low rate.',
    course_code: 'NURS 3813',
    topic: 'Beta Blockers',
    difficulty: 1,
  },
  {
    id: 'fc-p02',
    deck_id: 'deck-pharm',
    front: 'What are the hold parameters for beta-blockers?',
    back: 'Hold if HR < 60 bpm or SBP < 100 mmHg. Always check apical pulse for 1 full minute before giving.',
    course_code: 'NURS 3813',
    topic: 'Beta Blockers',
    difficulty: 1,
  },
  {
    id: 'fc-p03',
    deck_id: 'deck-pharm',
    front: 'Why should beta-blockers NEVER be stopped abruptly?',
    back: 'Abrupt discontinuation causes rebound tachycardia and hypertensive crisis due to upregulation of beta receptors during therapy. Always taper over 1-2 weeks.',
    hint: 'The heart overcompensates when the brake is suddenly removed.',
    course_code: 'NURS 3813',
    topic: 'Beta Blockers',
    difficulty: 2,
  },
  {
    id: 'fc-p04',
    deck_id: 'deck-pharm',
    front: 'How does carvedilol differ from metoprolol?',
    back: 'Carvedilol is a NON-selective beta-blocker (blocks beta-1, beta-2, AND alpha-1). The alpha-1 blockade provides additional vasodilation. Metoprolol is beta-1 SELECTIVE. Carvedilol causes more orthostatic hypotension and must be taken with food.',
    course_code: 'NURS 3813',
    topic: 'Beta Blockers',
    difficulty: 2,
  },
  {
    id: 'fc-p05',
    deck_id: 'deck-pharm',
    front: 'What drug class ends in "-pril"?',
    back: 'ACE inhibitors (e.g., lisinopril, enalapril). They inhibit angiotensin-converting enzyme, reducing vasoconstriction and aldosterone secretion.',
    hint: 'April showers = dry cough.',
    course_code: 'NURS 3813',
    topic: 'ACE Inhibitors',
    difficulty: 1,
  },
  {
    id: 'fc-p06',
    deck_id: 'deck-pharm',
    front: 'What is the hallmark side effect of ACE inhibitors and why does it occur?',
    back: 'Dry, persistent cough (10-15% of patients). ACE inhibitors prevent the breakdown of bradykinin, which accumulates in the lungs and irritates airways. If intolerable, switch to an ARB.',
    course_code: 'NURS 3813',
    topic: 'ACE Inhibitors',
    difficulty: 2,
  },
  {
    id: 'fc-p07',
    deck_id: 'deck-pharm',
    front: 'What lab values must you monitor with ACE inhibitors and ARBs?',
    back: 'Potassium (risk of hyperkalemia — hold if K+ > 5.0 mEq/L), BUN/creatinine (renal function), and blood pressure (hold if SBP < 90 mmHg). Both are contraindicated in pregnancy.',
    course_code: 'NURS 3813',
    topic: 'ACE Inhibitors',
    difficulty: 2,
  },
  {
    id: 'fc-p08',
    deck_id: 'deck-pharm',
    front: 'What is angioedema and which drug classes cause it?',
    back: 'Angioedema is rapid swelling of the face, lips, tongue, and/or airway — life-threatening. Caused by ACE inhibitors (more common) and ARBs (less common). Due to bradykinin accumulation. HOLD drug immediately and call provider.',
    course_code: 'NURS 3813',
    topic: 'ACE Inhibitors',
    difficulty: 3,
  },
  {
    id: 'fc-p09',
    deck_id: 'deck-pharm',
    front: 'What drug class ends in "-sartan"?',
    back: 'ARBs — Angiotensin II Receptor Blockers (e.g., losartan, valsartan). They block angiotensin II at the AT1 receptor. Unlike ACE inhibitors, they do NOT cause a dry cough because they do not affect bradykinin.',
    course_code: 'NURS 3813',
    topic: 'ARBs',
    difficulty: 1,
  },
  {
    id: 'fc-p10',
    deck_id: 'deck-pharm',
    front: 'What is Entresto and what is the critical safety concern?',
    back: 'Entresto = sacubitril/valsartan, used for HFrEF. Must NOT be given within 36 hours of an ACE inhibitor due to severe angioedema risk. Sacubitril inhibits neprilysin, which breaks down beneficial natriuretic peptides.',
    course_code: 'NURS 3813',
    topic: 'ARBs',
    difficulty: 3,
  },
  {
    id: 'fc-p11',
    deck_id: 'deck-pharm',
    front: 'What lab must you check BEFORE giving furosemide (Lasix)?',
    back: 'Potassium (K+). Loop diuretics cause potassium wasting. Hold if K+ < 3.5 mEq/L. Also check BP, BUN/creatinine, Na+, and Mg2+.',
    hint: 'Loop Loses potassium.',
    course_code: 'NURS 3813',
    topic: 'Loop Diuretics',
    difficulty: 1,
  },
  {
    id: 'fc-p12',
    deck_id: 'deck-pharm',
    front: 'What is the IV push rate for furosemide and why?',
    back: 'No faster than 20 mg/min. Rapid IV push causes ototoxicity (tinnitus, hearing loss). Also increases risk of hypotension.',
    course_code: 'NURS 3813',
    topic: 'Loop Diuretics',
    difficulty: 2,
  },
  {
    id: 'fc-p13',
    deck_id: 'deck-pharm',
    front: 'What is the potency equivalence between bumetanide and furosemide?',
    back: '1 mg bumetanide = 40 mg furosemide. Bumetanide (Bumex) is 40x more potent.',
    hint: 'Bumex BUMPS up the potency.',
    course_code: 'NURS 3813',
    topic: 'Loop Diuretics',
    difficulty: 2,
  },
  {
    id: 'fc-p14',
    deck_id: 'deck-pharm',
    front: 'Heparin: What lab test monitors it, what is therapeutic range, and what is the antidote?',
    back: 'aPTT (activated partial thromboplastin time). Therapeutic: 1.5-2.5x normal (approximately 46-70 seconds). Antidote: protamine sulfate (1 mg per 100 units heparin).',
    hint: 'HEParin = HEP me, aPTT!',
    course_code: 'NURS 3813',
    topic: 'Anticoagulants',
    difficulty: 2,
  },
  {
    id: 'fc-p15',
    deck_id: 'deck-pharm',
    front: 'Warfarin: What lab test monitors it, what is therapeutic range, and what is the antidote?',
    back: 'INR/PT (International Normalized Ratio / Prothrombin Time). Therapeutic INR: 2.0-3.0 (2.5-3.5 for mechanical heart valves). Antidote: Vitamin K (phytonadione); 4-factor PCC or FFP for emergent bleeding.',
    hint: 'PT/INR for ProThrombin = WarfariN.',
    course_code: 'NURS 3813',
    topic: 'Anticoagulants',
    difficulty: 2,
  },
  {
    id: 'fc-p16',
    deck_id: 'deck-pharm',
    front: 'What is HIT (Heparin-Induced Thrombocytopenia)?',
    back: 'An immune-mediated reaction where antibodies against heparin-platelet factor 4 complexes cause platelet activation and consumption. Platelets DROP > 50% from baseline, but paradoxically causes CLOTTING (not bleeding). Stop all heparin products immediately.',
    course_code: 'NURS 3813',
    topic: 'Anticoagulants',
    difficulty: 3,
  },
  {
    id: 'fc-p17',
    deck_id: 'deck-pharm',
    front: 'What is unique about enoxaparin (Lovenox) injection technique?',
    back: 'Sub-Q into abdominal fat only. Do NOT expel the air bubble from the prefilled syringe. Do NOT aspirate before injecting. Do NOT massage the site after. Alternate injection sides.',
    hint: 'Lovenox LOVES the belly.',
    course_code: 'NURS 3813',
    topic: 'Anticoagulants',
    difficulty: 2,
  },
  {
    id: 'fc-p18',
    deck_id: 'deck-pharm',
    front: 'List insulin types from fastest to slowest onset.',
    back: 'Rapid-acting (lispro/Humalog, aspart/Novolog): 15 min → Short-acting (regular/Humulin R): 30 min → Intermediate (NPH/Humulin N): 1-2 hr → Long-acting (glargine/Lantus): 1-2 hr (peakless, 24 hr duration).',
    course_code: 'NURS 3813',
    topic: 'Insulin',
    difficulty: 2,
  },
  {
    id: 'fc-p19',
    deck_id: 'deck-pharm',
    front: 'Which is the ONLY insulin that can be given IV?',
    back: 'Regular insulin (Humulin R, Novolin R). Used in DKA, HHS, and hyperkalemia. All other insulins are Sub-Q only.',
    hint: 'R = Runs through the IV.',
    course_code: 'NURS 3813',
    topic: 'Insulin',
    difficulty: 1,
  },
  {
    id: 'fc-p20',
    deck_id: 'deck-pharm',
    front: 'When mixing insulins, what is the correct draw-up order?',
    back: 'Draw Regular (clear) FIRST, then NPH (cloudy). "Clear before cloudy." "RN = Regular then NPH." Never mix glargine or detemir with any other insulin.',
    course_code: 'NURS 3813',
    topic: 'Insulin',
    difficulty: 1,
  },
  {
    id: 'fc-p21',
    deck_id: 'deck-pharm',
    front: 'What is the Rule of 15 for hypoglycemia?',
    back: 'If blood glucose < 70 mg/dL: give 15 g of fast-acting carbohydrates (4 oz juice, glucose tabs), wait 15 minutes, recheck blood glucose. Repeat if still < 70. Follow with a complex carb/protein snack once stable.',
    course_code: 'NURS 3813',
    topic: 'Insulin',
    difficulty: 1,
  },
  {
    id: 'fc-p22',
    deck_id: 'deck-pharm',
    front: 'Why must you check K+ before giving insulin in DKA?',
    back: 'Insulin drives potassium INTO cells, lowering serum K+. In DKA, total body K+ is already depleted (despite possibly normal or high serum K+ due to acidosis shifting K+ out of cells). If K+ < 3.3 mEq/L, replace potassium BEFORE starting insulin to prevent fatal hypokalemia/cardiac arrest.',
    course_code: 'NURS 3813',
    topic: 'Insulin',
    difficulty: 3,
  },
  {
    id: 'fc-p23',
    deck_id: 'deck-pharm',
    front: 'What are the three FDA black box warnings for fluoroquinolones (ciprofloxacin)?',
    back: '1) Tendon rupture/tendinitis (especially Achilles), 2) Peripheral neuropathy, 3) CNS effects (seizures, confusion, dizziness). Also avoid in children (cartilage damage) and pregnancy.',
    hint: 'CIPRO = Cartilage Injury, Peripheral neuropathy, Rupture, Oh no!',
    course_code: 'NURS 3813',
    topic: 'Antibiotics',
    difficulty: 2,
  },
  {
    id: 'fc-p24',
    deck_id: 'deck-pharm',
    front: 'What is Red Man Syndrome and how do you prevent it?',
    back: 'A histamine-mediated reaction to vancomycin caused by infusing too fast. Patient develops flushing, rash, and pruritus of the upper body. NOT a true allergy. Prevent by infusing over at least 60 minutes (1 g/60 min). If it occurs: stop infusion, give diphenhydramine, restart at a slower rate.',
    course_code: 'NURS 3813',
    topic: 'Antibiotics',
    difficulty: 2,
  },
  {
    id: 'fc-p25',
    deck_id: 'deck-pharm',
    front: 'What is the therapeutic vancomycin trough level and when do you draw it?',
    back: 'Trough: 10-20 mcg/mL (institution-dependent; AUC/MIC-guided dosing increasingly used). Draw trough 30 minutes BEFORE the 4th dose (at steady state). Monitor BUN/creatinine and hearing.',
    course_code: 'NURS 3813',
    topic: 'Antibiotics',
    difficulty: 3,
  },
  {
    id: 'fc-p26',
    deck_id: 'deck-pharm',
    front: 'What is the priority assessment before giving any opioid?',
    back: 'Respiratory rate. Hold if RR < 12 breaths/min. Also assess sedation level, pain score, blood pressure, and level of consciousness. Antidote for opioid overdose: naloxone (Narcan) 0.4 mg IV.',
    course_code: 'NURS 3813',
    topic: 'Opioids',
    difficulty: 1,
  },
  {
    id: 'fc-p27',
    deck_id: 'deck-pharm',
    front: 'Why is the hydromorphone/morphine confusion dangerous?',
    back: 'Hydromorphone (Dilaudid) is 5-7x MORE potent than morphine. If a morphine dose is accidentally given as hydromorphone, it can cause fatal respiratory depression. This is an ISMP high-alert look-alike/sound-alike error. Use Tall Man Lettering: HYDROmorphone.',
    course_code: 'NURS 3813',
    topic: 'Opioids',
    difficulty: 3,
  },
  {
    id: 'fc-p28',
    deck_id: 'deck-pharm',
    front: 'Why should you never crush OxyContin (extended-release oxycodone)?',
    back: 'Crushing destroys the extended-release mechanism, releasing the ENTIRE dose at once ("dose dumping"). This can cause fatal respiratory depression. ER formulations must be swallowed whole.',
    course_code: 'NURS 3813',
    topic: 'Opioids',
    difficulty: 2,
  },
  {
    id: 'fc-p29',
    deck_id: 'deck-pharm',
    front: 'What are the signs of statin-induced rhabdomyolysis?',
    back: 'Severe muscle pain/tenderness/weakness, dark brown (tea-colored) urine (myoglobinuria), elevated CK (> 10x upper limit of normal), elevated creatinine (renal failure from myoglobin). Hold statin and notify provider immediately.',
    course_code: 'NURS 3813',
    topic: 'Statins',
    difficulty: 2,
  },
  {
    id: 'fc-p30',
    deck_id: 'deck-pharm',
    front: 'What is the timing difference for simvastatin vs. atorvastatin?',
    back: 'Simvastatin: take in the EVENING (shorter half-life, cholesterol synthesis peaks at night). Atorvastatin: can be taken any time of day (long half-life).',
    hint: 'SIMvastatin = SIMply at Sunset.',
    course_code: 'NURS 3813',
    topic: 'Statins',
    difficulty: 1,
  },
  {
    id: 'fc-p31',
    deck_id: 'deck-pharm',
    front: 'When using both a SABA (albuterol) and an inhaled corticosteroid, which goes first?',
    back: 'Albuterol (SABA) FIRST. It opens the airways through bronchodilation, allowing the corticosteroid to penetrate deeper into the lungs for better effect.',
    hint: 'Open the door before walking in.',
    course_code: 'NURS 3813',
    topic: 'Bronchodilators',
    difficulty: 1,
  },
  {
    id: 'fc-p32',
    deck_id: 'deck-pharm',
    front: 'What indicates poorly controlled asthma regarding rescue inhaler use?',
    back: 'Using a rescue inhaler (SABA like albuterol) more than 2 days per week indicates uncontrolled asthma. Provider should be notified to step up maintenance therapy.',
    course_code: 'NURS 3813',
    topic: 'Bronchodilators',
    difficulty: 2,
  },
  {
    id: 'fc-p33',
    deck_id: 'deck-pharm',
    front: 'What is the FDA black box warning for salmeterol (LABA)?',
    back: 'Increased risk of asthma-related death when used as MONOTHERAPY. LABAs must ALWAYS be used with an inhaled corticosteroid for asthma (e.g., Advair = fluticasone + salmeterol). Never use a LABA as a rescue inhaler.',
    course_code: 'NURS 3813',
    topic: 'Bronchodilators',
    difficulty: 2,
  },
  {
    id: 'fc-p34',
    deck_id: 'deck-pharm',
    front: 'What are the hold parameters for digoxin in adults?',
    back: 'Hold if apical HR < 60 bpm, K+ < 3.5 mEq/L, or digoxin level > 2.0 ng/mL. Therapeutic range: 0.8-2.0 ng/mL. Hypokalemia INCREASES digoxin toxicity.',
    hint: 'DIG + low K = DIG your grave.',
    course_code: 'NURS 3813',
    topic: 'Cardiac Glycosides',
    difficulty: 2,
  },
  {
    id: 'fc-p35',
    deck_id: 'deck-pharm',
    front: 'What are the earliest signs of digoxin toxicity?',
    back: 'GI symptoms: anorexia, nausea, vomiting (earliest). Then visual changes: yellow-green halos, blurred vision. Then cardiac: bradycardia, heart block, new dysrhythmias. Antidote: Digoxin immune Fab (Digibind).',
    course_code: 'NURS 3813',
    topic: 'Cardiac Glycosides',
    difficulty: 2,
  },
  {
    id: 'fc-p36',
    deck_id: 'deck-pharm',
    front: 'Why must metformin be held 48 hours before and after IV contrast dye?',
    back: 'IV contrast is nephrotoxic. Metformin is renally excreted. If renal function declines from contrast, metformin accumulates and can cause fatal lactic acidosis. Hold 48 hours and verify renal function has returned to baseline before restarting.',
    course_code: 'NURS 3813',
    topic: 'Oral Antidiabetics',
    difficulty: 3,
  },
  {
    id: 'fc-p37',
    deck_id: 'deck-pharm',
    front: 'Name 5 medications classified as ISMP high-alert medications.',
    back: 'Insulin, heparin, warfarin, opioids (morphine, hydromorphone, oxycodone), and digoxin. These carry heightened risk of significant harm when used in error. Require independent double-checks.',
    course_code: 'NURS 3813',
    topic: 'Patient Safety',
    difficulty: 1,
  },
  {
    id: 'fc-p38',
    deck_id: 'deck-pharm',
    front: 'What teaching is essential for ALL patients on anticoagulants?',
    back: 'Use soft toothbrush, electric razor. Avoid contact sports. Report: bleeding gums, nosebleeds, blood in urine/stool, excessive bruising, tarry stools, coffee-ground emesis. Wear medical alert bracelet. Avoid NSAIDs/aspirin unless approved.',
    course_code: 'NURS 3813',
    topic: 'Anticoagulants',
    difficulty: 2,
  },
  {
    id: 'fc-p39',
    deck_id: 'deck-pharm',
    front: 'What is the difference between bactericidal and bacteriostatic antibiotics?',
    back: 'Bactericidal = KILLS bacteria (penicillins, cephalosporins, fluoroquinolones, vancomycin). Bacteriostatic = INHIBITS growth, relies on immune system to kill (tetracyclines, macrolides, sulfonamides). In immunocompromised patients, bactericidal is preferred.',
    course_code: 'NURS 3813',
    topic: 'Antibiotics',
    difficulty: 2,
  },
  {
    id: 'fc-p40',
    deck_id: 'deck-pharm',
    front: 'Why must you always obtain culture and sensitivity BEFORE the first antibiotic dose?',
    back: 'The antibiotic will start killing bacteria, altering the culture results and making it impossible to identify the causative organism or its sensitivities. However, do NOT delay the first dose waiting for results — obtain the specimen, then give the drug.',
    course_code: 'NURS 3813',
    topic: 'Antibiotics',
    difficulty: 1,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DECK 2 — NURS 3153 Health Assessment (30 cards)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'fc-a01',
    deck_id: 'deck-assess',
    front: 'What is the standard order of physical assessment techniques?',
    back: 'Inspection, Palpation, Percussion, Auscultation (IPPA). EXCEPTION: Abdomen = Inspection, Auscultation, Percussion, Palpation — auscultate BEFORE palpating/percussing to avoid altering bowel sounds.',
    hint: 'The abdomen breaks the rule.',
    course_code: 'NURS 3153',
    topic: 'Assessment Techniques',
    difficulty: 1,
  },
  {
    id: 'fc-a02',
    deck_id: 'deck-assess',
    front: 'Why is the abdominal assessment order different?',
    back: 'Auscultation is done BEFORE percussion and palpation because touching the abdomen can stimulate or alter bowel sounds, giving inaccurate findings. Order: Inspect → Auscultate → Percuss → Palpate.',
    course_code: 'NURS 3153',
    topic: 'Assessment Techniques',
    difficulty: 1,
  },
  {
    id: 'fc-a03',
    deck_id: 'deck-assess',
    front: 'What are normal breath sounds and where are they heard?',
    back: 'Vesicular: soft, low-pitched, rustling — heard over peripheral lung fields (most of the lungs). Bronchovesicular: moderate pitch — heard over main bronchi (between scapulae, anterior 1st-2nd intercostal space). Bronchial/Tubular: loud, high-pitched, hollow — heard over trachea. Bronchial sounds heard over the peripheral lung = ABNORMAL (consolidation).',
    course_code: 'NURS 3153',
    topic: 'Lung Sounds',
    difficulty: 2,
  },
  {
    id: 'fc-a04',
    deck_id: 'deck-assess',
    front: 'Describe crackles (rales): sound, cause, and associated conditions.',
    back: 'Sound: Discontinuous, popping/crackling sounds (like hair rubbing near your ear). Fine crackles = high-pitched (pulmonary fibrosis, early HF). Coarse crackles = low-pitched, louder (pneumonia, severe pulmonary edema, bronchitis). Cause: Air passing through fluid or reopening collapsed alveoli.',
    course_code: 'NURS 3153',
    topic: 'Lung Sounds',
    difficulty: 2,
  },
  {
    id: 'fc-a05',
    deck_id: 'deck-assess',
    front: 'Describe wheezes: sound, cause, and associated conditions.',
    back: 'Sound: Continuous, high-pitched, musical/whistling sounds, usually on EXPIRATION. Cause: Narrowed airways from bronchospasm, mucus, or inflammation. Conditions: Asthma (most classic), COPD, bronchitis. Inspiratory wheezes suggest more severe obstruction.',
    course_code: 'NURS 3153',
    topic: 'Lung Sounds',
    difficulty: 2,
  },
  {
    id: 'fc-a06',
    deck_id: 'deck-assess',
    front: 'Describe stridor: sound, cause, and significance.',
    back: 'Sound: High-pitched, harsh, crowing sound heard on INSPIRATION, often audible without stethoscope. Cause: Upper airway obstruction (laryngeal edema, croup, foreign body, epiglottitis). Significance: EMERGENCY — indicates significant airway obstruction. Prepare for potential intubation.',
    course_code: 'NURS 3153',
    topic: 'Lung Sounds',
    difficulty: 2,
  },
  {
    id: 'fc-a07',
    deck_id: 'deck-assess',
    front: 'What are the normal heart sounds and when do they occur?',
    back: 'S1 ("lub"): Closure of mitral and tricuspid (AV) valves at the START of systole. Best heard at apex. S2 ("dub"): Closure of aortic and pulmonic (semilunar) valves at the END of systole. Best heard at the base (2nd intercostal space). S1-S2 = one heartbeat.',
    course_code: 'NURS 3153',
    topic: 'Heart Sounds',
    difficulty: 1,
  },
  {
    id: 'fc-a08',
    deck_id: 'deck-assess',
    front: 'What is an S3 heart sound and what does it indicate?',
    back: 'S3 ("Kentucky"): Low-pitched sound heard early in diastole, just after S2, at the apex with the bell. Sounds like "Ken-TUC-ky" (S1-S2-S3). Normal in children and young adults. In adults > 30: pathological — indicates heart failure (volume overload, ventricular dilation).',
    hint: 'S3 = heart failure = fluid (3 chambers full).',
    course_code: 'NURS 3153',
    topic: 'Heart Sounds',
    difficulty: 2,
  },
  {
    id: 'fc-a09',
    deck_id: 'deck-assess',
    front: 'What is an S4 heart sound and what does it indicate?',
    back: 'S4 ("Tennessee"): Low-pitched sound heard late in diastole, just before S1, at the apex with the bell. Sounds like "TEN-nes-see" (S4-S1-S2). Always pathological. Indicates stiff/non-compliant ventricle (LVH, hypertension, aortic stenosis, CAD). Atrial kick against a stiff ventricle.',
    hint: 'S4 = Stiff ventricle (4 = stiff = Stifffff).',
    course_code: 'NURS 3153',
    topic: 'Heart Sounds',
    difficulty: 2,
  },
  {
    id: 'fc-a10',
    deck_id: 'deck-assess',
    front: 'What are the 5 cardiac auscultation areas and their locations?',
    back: 'Aortic: 2nd ICS, right sternal border. Pulmonic: 2nd ICS, left sternal border. Erb\'s point: 3rd ICS, left sternal border. Tricuspid: 4th ICS, left sternal border. Mitral (apex): 5th ICS, left midclavicular line. Mnemonic: "All Patients Eat The Meal" or "APE To Man."',
    course_code: 'NURS 3153',
    topic: 'Heart Sounds',
    difficulty: 1,
  },
  {
    id: 'fc-a11',
    deck_id: 'deck-assess',
    front: 'What are normal bowel sounds?',
    back: 'Irregular gurgling/clicking sounds, occurring 5-30 times per minute. Auscultate all 4 quadrants. Listen for at least 5 minutes in EACH quadrant before documenting "absent." Hypoactive: < 5/min (post-surgery, paralytic ileus). Hyperactive: > 30/min, loud, high-pitched (diarrhea, early obstruction, gastroenteritis).',
    course_code: 'NURS 3153',
    topic: 'Abdominal Assessment',
    difficulty: 2,
  },
  {
    id: 'fc-a12',
    deck_id: 'deck-assess',
    front: 'What is the difference between light and deep palpation of the abdomen?',
    back: 'Light palpation: 1 cm depth, performed first. Assesses tenderness, muscle resistance, and superficial organs. Deep palpation: 4-6 cm depth, done after light. Assesses organ size (liver, spleen, kidneys), masses, and deep tenderness. Always palpate painful area LAST.',
    course_code: 'NURS 3153',
    topic: 'Abdominal Assessment',
    difficulty: 2,
  },
  {
    id: 'fc-a13',
    deck_id: 'deck-assess',
    front: 'What is a positive Blumberg sign (rebound tenderness) and what does it suggest?',
    back: 'Press deeply into the abdomen, then quickly release. Pain upon RELEASE (not pressing) = positive rebound tenderness. Suggests peritoneal inflammation — classic for appendicitis (McBurney\'s point: RLQ, 1/3 distance from ASIS to umbilicus). Also seen in peritonitis.',
    course_code: 'NURS 3153',
    topic: 'Abdominal Assessment',
    difficulty: 3,
  },
  {
    id: 'fc-a14',
    deck_id: 'deck-assess',
    front: 'What are the components of a neurological assessment using the Glasgow Coma Scale (GCS)?',
    back: 'Eye opening (1-4): 4=spontaneous, 3=to voice, 2=to pain, 1=none. Verbal response (1-5): 5=oriented, 4=confused, 3=inappropriate words, 2=incomprehensible sounds, 1=none. Motor response (1-6): 6=obeys commands, 5=localizes pain, 4=withdraws, 3=abnormal flexion, 2=extension, 1=none. Total: 3-15. ≤8 = severe (comatose, intubation likely).',
    course_code: 'NURS 3153',
    topic: 'Neurological Assessment',
    difficulty: 2,
  },
  {
    id: 'fc-a15',
    deck_id: 'deck-assess',
    front: 'How do you assess pupil response and what is abnormal?',
    back: 'Use penlight: shine in one eye, observe for direct response (same eye constricts) and consensual response (opposite eye constricts). Document PERRLA: Pupils Equal, Round, Reactive to Light and Accommodation. Abnormal: unequal pupils (anisocoria), fixed/dilated ("blown pupil" = increased ICP), pinpoint (opioid overdose).',
    course_code: 'NURS 3153',
    topic: 'Neurological Assessment',
    difficulty: 2,
  },
  {
    id: 'fc-a16',
    deck_id: 'deck-assess',
    front: 'What are the 12 cranial nerves and a quick test for each?',
    back: 'I Olfactory: smell. II Optic: visual acuity/fields. III Oculomotor: pupil constriction, eye movement. IV Trochlear: downward/inward gaze. V Trigeminal: facial sensation, jaw clench. VI Abducens: lateral gaze. VII Facial: smile, frown, raise brows. VIII Vestibulocochlear: hearing. IX Glossopharyngeal: gag reflex, say "ah." X Vagus: swallow, gag, voice. XI Accessory: shrug shoulders. XII Hypoglossal: tongue movement.',
    hint: 'Oh Oh Oh To Touch And Feel Very Good Velvet AH.',
    course_code: 'NURS 3153',
    topic: 'Neurological Assessment',
    difficulty: 3,
  },
  {
    id: 'fc-a17',
    deck_id: 'deck-assess',
    front: 'What is normal capillary refill time and what does prolonged refill indicate?',
    back: 'Normal: < 3 seconds (press nail bed, release, color returns in < 3 sec). Prolonged (> 3 seconds) indicates decreased peripheral perfusion — dehydration, shock, peripheral vascular disease, hypothermia, or anemia.',
    course_code: 'NURS 3153',
    topic: 'Cardiovascular Assessment',
    difficulty: 1,
  },
  {
    id: 'fc-a18',
    deck_id: 'deck-assess',
    front: 'What is the difference between pitting and non-pitting edema?',
    back: 'Pitting edema: press on swollen area for 5 seconds — indentation remains. Graded 1+ (2mm, slight) to 4+ (8mm, deep, > 30 sec to rebound). Causes: HF, renal failure, venous insufficiency. Non-pitting: no indentation. Causes: lymphedema, myxedema (hypothyroidism).',
    course_code: 'NURS 3153',
    topic: 'Cardiovascular Assessment',
    difficulty: 2,
  },
  {
    id: 'fc-a19',
    deck_id: 'deck-assess',
    front: 'How do you assess for orthostatic hypotension?',
    back: 'Measure BP and HR while supine (after 5 min), then sitting (1-3 min), then standing (1-3 min). Positive orthostatic hypotension: SBP drops ≥ 20 mmHg OR DBP drops ≥ 10 mmHg OR HR increases ≥ 20 bpm upon position change. Ensure patient safety — fall risk.',
    course_code: 'NURS 3153',
    topic: 'Cardiovascular Assessment',
    difficulty: 2,
  },
  {
    id: 'fc-a20',
    deck_id: 'deck-assess',
    front: 'What does JVD (Jugular Venous Distention) indicate?',
    back: 'Visible distension of the internal jugular vein when the patient is positioned at 45 degrees. Indicates increased central venous pressure. Most commonly seen in RIGHT-sided heart failure, cardiac tamponade, tension pneumothorax, and fluid overload.',
    course_code: 'NURS 3153',
    topic: 'Cardiovascular Assessment',
    difficulty: 2,
  },
  {
    id: 'fc-a21',
    deck_id: 'deck-assess',
    front: 'What is a focused respiratory assessment?',
    back: 'Rate (12-20/min adults), rhythm (regular vs irregular), depth, effort (use of accessory muscles, nasal flaring, retractions), O2 sat (≥ 95% normal, ≥ 88% acceptable for COPD), lung sounds bilaterally, cough (productive vs dry), sputum (color, amount, consistency), skin color (cyanosis = late sign).',
    course_code: 'NURS 3153',
    topic: 'Respiratory Assessment',
    difficulty: 1,
  },
  {
    id: 'fc-a22',
    deck_id: 'deck-assess',
    front: 'What is tactile fremitus and what do abnormalities indicate?',
    back: 'Vibration felt through the chest wall when patient says "ninety-nine." Place ulnar side of hands on posterior chest. Increased fremitus = consolidation (pneumonia, tumor) — denser tissue transmits vibration better. Decreased/absent fremitus = air or fluid barrier (pneumothorax, pleural effusion, COPD).',
    course_code: 'NURS 3153',
    topic: 'Respiratory Assessment',
    difficulty: 3,
  },
  {
    id: 'fc-a23',
    deck_id: 'deck-assess',
    front: 'What are normal vital signs for an adult?',
    back: 'Temperature: 97.8-99.1°F (36.5-37.3°C). Pulse: 60-100 bpm. Respirations: 12-20/min. BP: < 120/80 mmHg (normal), 120-129/<80 (elevated), 130-139/80-89 (Stage 1 HTN), ≥ 140/≥ 90 (Stage 2 HTN). O2 Sat: ≥ 95%.',
    course_code: 'NURS 3153',
    topic: 'Vital Signs',
    difficulty: 1,
  },
  {
    id: 'fc-a24',
    deck_id: 'deck-assess',
    front: 'What is a Braden Scale and what does it assess?',
    back: 'Assesses risk for pressure injury. 6 subscales: sensory perception, moisture, activity, mobility, nutrition, friction/shear. Each scored 1-4 (friction/shear 1-3). Total: 6-23. Score ≤ 18 = at risk. ≤ 12 = high risk. Lower score = higher risk.',
    course_code: 'NURS 3153',
    topic: 'Integumentary Assessment',
    difficulty: 2,
  },
  {
    id: 'fc-a25',
    deck_id: 'deck-assess',
    front: 'What are the stages of pressure injuries?',
    back: 'Stage 1: Non-blanchable erythema, intact skin. Stage 2: Partial-thickness skin loss, shallow open ulcer, may see blister. Stage 3: Full-thickness skin loss, subcutaneous fat visible, no bone/tendon/muscle exposed. Stage 4: Full-thickness tissue loss with exposed bone, tendon, or muscle. Unstageable: Obscured by slough/eschar. Deep tissue injury: Intact skin with purple/maroon discoloration.',
    course_code: 'NURS 3153',
    topic: 'Integumentary Assessment',
    difficulty: 2,
  },
  {
    id: 'fc-a26',
    deck_id: 'deck-assess',
    front: 'What is a dermatome and why does it matter in assessment?',
    back: 'A dermatome is an area of skin innervated by a single spinal nerve root. Mapping dermatomes helps localize spinal cord injuries or nerve compression. Example: C6 = thumb, T4 = nipple line, T10 = umbilicus, L5 = big toe dorsum, S1 = lateral foot.',
    course_code: 'NURS 3153',
    topic: 'Neurological Assessment',
    difficulty: 3,
  },
  {
    id: 'fc-a27',
    deck_id: 'deck-assess',
    front: 'What does a positive Homans sign suggest (and what is the current evidence)?',
    back: 'Calf pain on dorsiflexion of the foot was traditionally associated with DVT. However, it has poor sensitivity and specificity (many false positives/negatives) and is no longer recommended as a reliable diagnostic test. Better: assess for unilateral calf swelling, warmth, redness, tenderness. Confirm with Doppler ultrasound.',
    course_code: 'NURS 3153',
    topic: 'Cardiovascular Assessment',
    difficulty: 3,
  },
  {
    id: 'fc-a28',
    deck_id: 'deck-assess',
    front: 'What are Korotkoff sounds and how do they relate to BP measurement?',
    back: 'Sounds heard through stethoscope during manual BP measurement. Phase 1 (first sound heard) = systolic BP. Sounds change quality through phases 2-4. Phase 5 (last sound heard / silence) = diastolic BP. Proper technique: inflate 20-30 mmHg above where radial pulse disappears, deflate at 2-3 mmHg/second.',
    course_code: 'NURS 3153',
    topic: 'Vital Signs',
    difficulty: 2,
  },
  {
    id: 'fc-a29',
    deck_id: 'deck-assess',
    front: 'What is the difference between a bruit and a murmur?',
    back: 'Both are abnormal vascular sounds caused by turbulent blood flow. Murmur: heard over the heart, caused by valve abnormalities or septal defects. Bruit: heard over a peripheral artery (carotid, renal, femoral), caused by arterial narrowing/stenosis. A carotid bruit may indicate carotid artery stenosis and stroke risk.',
    course_code: 'NURS 3153',
    topic: 'Cardiovascular Assessment',
    difficulty: 2,
  },
  {
    id: 'fc-a30',
    deck_id: 'deck-assess',
    front: 'What is clubbing of the fingers and what does it indicate?',
    back: 'Enlargement of the fingertips with softening of the nail bed and loss of the normal angle (Lovibond angle > 180°). Indicates chronic hypoxia. Associated with: COPD, lung cancer, cystic fibrosis, congenital heart disease, endocarditis. Takes weeks to develop — chronic, not acute.',
    course_code: 'NURS 3153',
    topic: 'Respiratory Assessment',
    difficulty: 2,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DECK 3 — NURS 3193 Foundations of Nursing (30 cards)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'fc-f01',
    deck_id: 'deck-foundations',
    front: 'What are the 5 steps of the nursing process (ADPIE)?',
    back: 'Assessment: Collect data (subjective + objective). Diagnosis: Identify nursing diagnoses (not medical diagnoses). Planning: Set goals and outcomes (SMART goals). Implementation: Carry out nursing interventions. Evaluation: Determine if goals were met — if not, reassess and revise plan.',
    hint: 'A Delicious PIE.',
    course_code: 'NURS 3193',
    topic: 'Nursing Process',
    difficulty: 1,
  },
  {
    id: 'fc-f02',
    deck_id: 'deck-foundations',
    front: 'What is the difference between a nursing diagnosis and a medical diagnosis?',
    back: 'Nursing diagnosis: Describes a patient\'s response to a health condition that nurses can independently treat (e.g., "Impaired gas exchange related to fluid in alveoli as evidenced by O2 sat 88%"). Medical diagnosis: Identifies the disease/condition, made by a physician (e.g., "Heart failure"). Nurses treat the human response, not the disease.',
    course_code: 'NURS 3193',
    topic: 'Nursing Process',
    difficulty: 1,
  },
  {
    id: 'fc-f03',
    deck_id: 'deck-foundations',
    front: 'What are the 6 QSEN competencies?',
    back: 'Patient-centered care, Teamwork and collaboration, Evidence-based practice (EBP), Quality improvement (QI), Safety, Informatics. These guide nursing education to improve quality and safety in healthcare.',
    hint: 'Think: "Patients Team up with Evidence for Quality Safe Informatics."',
    course_code: 'NURS 3193',
    topic: 'QSEN',
    difficulty: 1,
  },
  {
    id: 'fc-f04',
    deck_id: 'deck-foundations',
    front: 'What is Maslow\'s Hierarchy of Needs in order, and how does it apply to clinical prioritization?',
    back: 'Bottom to top: 1) Physiological (airway, breathing, food, water, elimination), 2) Safety/Security (fall prevention, infection control, medication safety), 3) Love/Belonging (family, social support), 4) Esteem (independence, dignity), 5) Self-actualization (goals, growth). In clinical priority setting: always address lower-level needs FIRST. A patient who cannot breathe takes priority over a patient who is lonely.',
    course_code: 'NURS 3193',
    topic: 'Priority Setting',
    difficulty: 1,
  },
  {
    id: 'fc-f05',
    deck_id: 'deck-foundations',
    front: 'What are the 6 rights of medication administration?',
    back: 'Right patient (2 identifiers), Right medication, Right dose, Right route, Right time, Right documentation. Additional rights often included: Right reason, Right to refuse, Right assessment, Right education, Right evaluation.',
    course_code: 'NURS 3193',
    topic: 'Medication Safety',
    difficulty: 1,
  },
  {
    id: 'fc-f06',
    deck_id: 'deck-foundations',
    front: 'What are the 2 patient identifiers and when must they be used?',
    back: 'Full name + date of birth (or medical record number) — use TWO identifiers. Must be used before: administering medications, blood products, lab draws, procedures, meals (dietary restrictions). NEVER use room number as an identifier.',
    course_code: 'NURS 3193',
    topic: 'Patient Safety',
    difficulty: 1,
  },
  {
    id: 'fc-f07',
    deck_id: 'deck-foundations',
    front: 'What are standard precautions?',
    back: 'Applied to ALL patients regardless of diagnosis. Assume all blood, body fluids, non-intact skin, and mucous membranes are potentially infectious. Includes: hand hygiene, gloves, gowns (when splash risk), masks/eye protection, safe sharps handling, respiratory hygiene/cough etiquette. Hand hygiene is the #1 method to prevent infection.',
    course_code: 'NURS 3193',
    topic: 'Infection Control',
    difficulty: 1,
  },
  {
    id: 'fc-f08',
    deck_id: 'deck-foundations',
    front: 'What are the types of transmission-based precautions?',
    back: 'Contact (MRSA, C. diff, VRE, scabies): Gown + gloves, dedicated equipment. Droplet (Influenza, pertussis, meningococcal, strep pharyngitis): Surgical mask within 3 feet. Airborne (TB, measles, varicella/chickenpox): N95 respirator, negative-pressure room. Mnemonic: "My Chicken has TB" = Measles, Chickenpox, TB = airborne.',
    course_code: 'NURS 3193',
    topic: 'Infection Control',
    difficulty: 2,
  },
  {
    id: 'fc-f09',
    deck_id: 'deck-foundations',
    front: 'What PPE is required for C. difficile and why is alcohol-based hand rub insufficient?',
    back: 'Contact precautions: gown + gloves. C. diff forms spores that are resistant to alcohol-based hand sanitizer. Must wash with SOAP AND WATER for at least 20 seconds. Also requires dedicated equipment and thorough environmental cleaning with bleach-based disinfectant.',
    course_code: 'NURS 3193',
    topic: 'Infection Control',
    difficulty: 2,
  },
  {
    id: 'fc-f10',
    deck_id: 'deck-foundations',
    front: 'What is SBAR and when is it used?',
    back: 'Communication framework for nurse-to-provider or nurse-to-nurse handoff. S = Situation (what is happening), B = Background (relevant history), A = Assessment (what you found/think), R = Recommendation (what you need). Example: "Dr. Smith, I\'m calling about Mr. Jones in 412. His BP dropped to 82/50. He has a history of heart failure. I assessed him — he is diaphoretic with weak pulses. I recommend a fluid bolus and you come evaluate."',
    course_code: 'NURS 3193',
    topic: 'Communication',
    difficulty: 1,
  },
  {
    id: 'fc-f11',
    deck_id: 'deck-foundations',
    front: 'What is the chain of infection and how can nurses break each link?',
    back: 'Infectious agent → Reservoir → Portal of exit → Mode of transmission → Portal of entry → Susceptible host. Break it: Hand hygiene (transmission), PPE (portal of entry/exit), sterile technique (agent), immunizations (host susceptibility), environmental cleaning (reservoir), respiratory etiquette (portal of exit).',
    course_code: 'NURS 3193',
    topic: 'Infection Control',
    difficulty: 2,
  },
  {
    id: 'fc-f12',
    deck_id: 'deck-foundations',
    front: 'What are the principles of surgical asepsis (sterile technique)?',
    back: 'Only sterile items touch sterile field. Sterile field created just before use, never left unattended. If in doubt about sterility, consider it contaminated. 1-inch border of sterile drape is non-sterile. Avoid reaching over the sterile field. Keep sterile items above waist level. A wet sterile field is contaminated (strike-through). Face the sterile field at all times.',
    course_code: 'NURS 3193',
    topic: 'Infection Control',
    difficulty: 2,
  },
  {
    id: 'fc-f13',
    deck_id: 'deck-foundations',
    front: 'What is the difference between negligence and malpractice?',
    back: 'Negligence: Failure to exercise the care that a reasonably prudent person would exercise (general standard). Malpractice: Professional negligence — failure to meet the standard of care expected of a professional (nurse) that results in harm. 4 elements: Duty, Breach of duty, Causation (proximate cause), Damages (harm). Example: Not checking blood glucose before insulin → patient has hypoglycemic seizure.',
    course_code: 'NURS 3193',
    topic: 'Legal/Ethical',
    difficulty: 2,
  },
  {
    id: 'fc-f14',
    deck_id: 'deck-foundations',
    front: 'What are the 4 ethical principles in nursing?',
    back: 'Autonomy: Patient\'s right to make informed decisions about their care (informed consent, right to refuse). Beneficence: Duty to do good. Nonmaleficence: "Do no harm." Justice: Fair and equitable treatment for all patients. Additional: Fidelity (faithfulness/promise keeping), Veracity (truth-telling).',
    course_code: 'NURS 3193',
    topic: 'Legal/Ethical',
    difficulty: 1,
  },
  {
    id: 'fc-f15',
    deck_id: 'deck-foundations',
    front: 'What is informed consent and what are the nurse\'s responsibilities?',
    back: 'The provider obtains informed consent by explaining: procedure, risks, benefits, alternatives, and consequences of refusal. The NURSE\'S role: verify the consent form is signed, ensure the patient understands (advocate), witness the signature. If the patient does not understand, STOP the process and notify the provider. The nurse does NOT explain the procedure — that is the provider\'s duty.',
    course_code: 'NURS 3193',
    topic: 'Legal/Ethical',
    difficulty: 2,
  },
  {
    id: 'fc-f16',
    deck_id: 'deck-foundations',
    front: 'What is the difference between an advance directive and a DNR?',
    back: 'Advance directive: Legal document expressing a patient\'s healthcare wishes when they cannot speak for themselves. Includes living will (specific treatments accepted/refused) and durable power of attorney for healthcare (designates a surrogate decision-maker). DNR (Do Not Resuscitate): Specific order by a provider (with patient/surrogate consent) to not perform CPR in the event of cardiac/respiratory arrest. A DNR does NOT mean "do not treat" — all other care continues.',
    course_code: 'NURS 3193',
    topic: 'Legal/Ethical',
    difficulty: 2,
  },
  {
    id: 'fc-f17',
    deck_id: 'deck-foundations',
    front: 'What are the 5 moments of hand hygiene (WHO)?',
    back: '1) Before touching a patient, 2) Before a clean/aseptic procedure, 3) After body fluid exposure risk, 4) After touching a patient, 5) After touching patient surroundings. Use alcohol-based hand rub (ABHR) for most situations. Use soap and water when: hands are visibly soiled, C. difficile, after using the restroom.',
    course_code: 'NURS 3193',
    topic: 'Infection Control',
    difficulty: 1,
  },
  {
    id: 'fc-f18',
    deck_id: 'deck-foundations',
    front: 'What is the correct order for donning and doffing PPE?',
    back: 'Donning (putting on): Gown → Mask/Respirator → Goggles/Face shield → Gloves. Doffing (removing): Gloves → Goggles/Face shield → Gown → Mask/Respirator. Doff = reverse order, gloves first (most contaminated). Hand hygiene between steps and after all PPE is removed.',
    course_code: 'NURS 3193',
    topic: 'Infection Control',
    difficulty: 2,
  },
  {
    id: 'fc-f19',
    deck_id: 'deck-foundations',
    front: 'What are the components of a complete head-to-toe assessment?',
    back: 'General survey (appearance, LOC, distress) → Vital signs → Neurological (orientation, pupils, GCS) → Head/eyes/ears/nose/throat → Respiratory (lung sounds, effort, O2 sat) → Cardiovascular (heart sounds, pulses, edema, cap refill) → Abdomen (bowel sounds, tenderness, distension) → Musculoskeletal (ROM, strength) → Integumentary (skin integrity, wounds, turgor) → Psychosocial (mood, safety).',
    course_code: 'NURS 3193',
    topic: 'Assessment',
    difficulty: 1,
  },
  {
    id: 'fc-f20',
    deck_id: 'deck-foundations',
    front: 'What is HIPAA and how does it apply to nursing students?',
    back: 'Health Insurance Portability and Accountability Act. Protects patient health information (PHI) privacy. Nurses/students: Do NOT discuss patients in public areas (elevators, cafeteria). Do NOT photograph patients or medical records. Do NOT post anything about patients on social media. Only access medical records for patients assigned to you. Violations can result in fines, termination, or criminal charges.',
    course_code: 'NURS 3193',
    topic: 'Legal/Ethical',
    difficulty: 1,
  },
  {
    id: 'fc-f21',
    deck_id: 'deck-foundations',
    front: 'What is the difference between restraints and alternatives, and when are restraints appropriate?',
    back: 'Alternatives first: bed alarm, sitter, reorientation, move patient closer to nursing station, remove lines if possible, address underlying cause (pain, full bladder, hypoxia). Restraints = LAST resort. Require a provider order. Assess circulation/sensation every 1-2 hours. Remove and assess skin, offer food/fluids/toileting every 2 hours. Orders must be renewed every 24 hours (non-violent) or per policy.',
    course_code: 'NURS 3193',
    topic: 'Patient Safety',
    difficulty: 2,
  },
  {
    id: 'fc-f22',
    deck_id: 'deck-foundations',
    front: 'What is the proper technique for administering a subcutaneous injection?',
    back: '90-degree angle for most adults (45 degrees for thin patients). Pinch skin fold. Preferred sites: abdomen, upper arm, anterior thigh. Do NOT aspirate for sub-Q injections (no longer recommended). For heparin/insulin: do NOT massage after injection. Rotate sites. Needle length: typically 5/8 inch.',
    course_code: 'NURS 3193',
    topic: 'Medication Administration',
    difficulty: 2,
  },
  {
    id: 'fc-f23',
    deck_id: 'deck-foundations',
    front: 'What is the proper technique for administering an intramuscular (IM) injection?',
    back: '90-degree angle. Z-track technique for all IM injections (prevents medication tracking through tissue). Preferred site: ventrogluteal (safest, no major nerves/vessels). Vastus lateralis for infants. Deltoid for small volumes (< 1 mL) in adults. Aspiration before injection is no longer recommended by the CDC for most IM injections.',
    course_code: 'NURS 3193',
    topic: 'Medication Administration',
    difficulty: 2,
  },
  {
    id: 'fc-f24',
    deck_id: 'deck-foundations',
    front: 'What are the 5 stages of Erikson\'s development for adults and how does it apply to patient care?',
    back: 'Young adult (18-40): Intimacy vs. Isolation. Middle adult (40-65): Generativity vs. Stagnation. Older adult (65+): Ego Integrity vs. Despair. Application: A young adult newly diagnosed with chronic illness may struggle with relationships and body image. An older adult facing terminal illness needs support to find meaning and peace with their life.',
    course_code: 'NURS 3193',
    topic: 'Growth & Development',
    difficulty: 2,
  },
  {
    id: 'fc-f25',
    deck_id: 'deck-foundations',
    front: 'What are the components of documenting nursing care?',
    back: 'Must be: Factual (objective data), Accurate, Complete, Timely (document as close to the event as possible), Organized. Never: chart in advance, alter records, use correction fluid. Late entries must be labeled as such. Use approved abbreviations only. "If it wasn\'t documented, it wasn\'t done." Document assessments, interventions, patient responses, and communications with providers.',
    course_code: 'NURS 3193',
    topic: 'Documentation',
    difficulty: 1,
  },
  {
    id: 'fc-f26',
    deck_id: 'deck-foundations',
    front: 'What is the scope of practice for an RN vs. LPN/LVN vs. UAP?',
    back: 'RN: Assessment, care planning, complex interventions, teaching, evaluation, delegation, IV meds. LPN/LVN: Can collect data (not initial assessment), administer PO/IM/Sub-Q meds, perform dressing changes, maintain IV (varies by state). UAP (CNA/Tech): Vital signs, bathing, ambulation, feeding, I&O, daily weights. NEVER delegate: Assessment, Teaching, Evaluation, or any skill requiring clinical judgment to UAP.',
    course_code: 'NURS 3193',
    topic: 'Delegation',
    difficulty: 2,
  },
  {
    id: 'fc-f27',
    deck_id: 'deck-foundations',
    front: 'What are the 5 rights of delegation?',
    back: 'Right task (can it be delegated?), Right circumstance (is the patient stable?), Right person (is the delegate competent?), Right direction/communication (clear instructions and expectations), Right supervision/evaluation (follow up on outcomes). Use "ATE" to remember what CANNOT be delegated: Assessment, Teaching, Evaluation.',
    course_code: 'NURS 3193',
    topic: 'Delegation',
    difficulty: 2,
  },
  {
    id: 'fc-f28',
    deck_id: 'deck-foundations',
    front: 'What are modifiable vs. non-modifiable risk factors for falls?',
    back: 'Modifiable: medications (sedatives, antihypertensives, diuretics), environmental hazards (wet floors, poor lighting, clutter), inappropriate footwear, deconditioning, postural hypotension. Non-modifiable: age > 65, history of falls, cognitive impairment, visual impairment, chronic conditions. Interventions: bed alarm, non-skid socks, call light in reach, toileting schedule, low bed position.',
    course_code: 'NURS 3193',
    topic: 'Patient Safety',
    difficulty: 2,
  },
  {
    id: 'fc-f29',
    deck_id: 'deck-foundations',
    front: 'What is evidence-based practice (EBP) and what are its components?',
    back: 'EBP integrates three components: 1) Best research evidence, 2) Clinical expertise, and 3) Patient values and preferences. Steps: Ask a clinical question (PICO format), search for evidence, critically appraise the evidence, integrate with clinical expertise and patient values, evaluate outcomes.',
    course_code: 'NURS 3193',
    topic: 'Evidence-Based Practice',
    difficulty: 2,
  },
  {
    id: 'fc-f30',
    deck_id: 'deck-foundations',
    front: 'What is the difference between subjective and objective data?',
    back: 'Subjective data: What the patient TELLS you (symptoms). Cannot be measured or verified independently. Examples: "I feel dizzy," "My pain is 8/10," "I am scared." Objective data: What you OBSERVE or MEASURE (signs). Examples: BP 160/95, O2 sat 91%, diaphoretic, grimacing. Both are essential for comprehensive assessment.',
    course_code: 'NURS 3193',
    topic: 'Nursing Process',
    difficulty: 1,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DECK 4 — BIOL 4344 Pathophysiology (30 cards)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'fc-pt01',
    deck_id: 'deck-patho',
    front: 'What is the pathophysiology of left-sided heart failure?',
    back: 'The left ventricle fails to pump blood effectively to systemic circulation → blood backs up into the LEFT atrium → then into the PULMONARY veins → pulmonary congestion and edema. Key signs: Dyspnea, orthopnea, crackles in lungs, paroxysmal nocturnal dyspnea (PND), cough with frothy sputum, decreased cardiac output, fatigue, S3 gallop.',
    hint: 'Left = Lung. Blood backs up into the lungs.',
    course_code: 'BIOL 4344',
    topic: 'Heart Failure',
    difficulty: 2,
  },
  {
    id: 'fc-pt02',
    deck_id: 'deck-patho',
    front: 'What is the pathophysiology of right-sided heart failure?',
    back: 'The right ventricle fails to pump blood effectively to the lungs → blood backs up into the RIGHT atrium → then into the SYSTEMIC venous circulation. Most commonly caused by left-sided HF. Key signs: JVD, peripheral edema (dependent), hepatomegaly, splenomegaly, ascites, weight gain.',
    hint: 'Right = Rest of the body. Systemic congestion.',
    course_code: 'BIOL 4344',
    topic: 'Heart Failure',
    difficulty: 2,
  },
  {
    id: 'fc-pt03',
    deck_id: 'deck-patho',
    front: 'What is the difference between HFrEF and HFpEF?',
    back: 'HFrEF (systolic failure): EF < 40%. Heart cannot CONTRACT effectively — dilated, weak ventricle. Causes: MI, dilated cardiomyopathy. Treatment: ACE-I/ARB, beta-blocker, diuretics, Entresto. HFpEF (diastolic failure): EF ≥ 50%. Heart cannot RELAX/FILL effectively — stiff, hypertrophied ventricle. Causes: HTN, aortic stenosis, hypertrophic cardiomyopathy. Treatment: manage volume (diuretics), treat underlying cause.',
    course_code: 'BIOL 4344',
    topic: 'Heart Failure',
    difficulty: 3,
  },
  {
    id: 'fc-pt04',
    deck_id: 'deck-patho',
    front: 'What is the pathophysiology of COPD (chronic bronchitis vs. emphysema)?',
    back: 'Chronic bronchitis ("Blue Bloater"): Chronic inflammation → excess mucus production → airway obstruction → V/Q mismatch → hypoxemia and hypercapnia. Productive cough ≥ 3 months/year for 2+ consecutive years. Emphysema ("Pink Puffer"): Destruction of alveolar walls → loss of elastic recoil → air trapping → hyperinflation → decreased gas exchange surface area. Barrel chest, pursed-lip breathing, dyspnea.',
    course_code: 'BIOL 4344',
    topic: 'COPD',
    difficulty: 2,
  },
  {
    id: 'fc-pt05',
    deck_id: 'deck-patho',
    front: 'Why must you use LOW-flow oxygen (1-2 L/min) in COPD patients?',
    back: 'Chronic CO2 retention → central chemoreceptors become desensitized to CO2. The body relies on HYPOXIC DRIVE (low O2 sensed by peripheral chemoreceptors) to trigger breathing. Giving high-flow O2 removes the hypoxic drive → respiratory depression/arrest. Target O2 sat: 88-92% for COPD patients (not 95%+).',
    course_code: 'BIOL 4344',
    topic: 'COPD',
    difficulty: 3,
  },
  {
    id: 'fc-pt06',
    deck_id: 'deck-patho',
    front: 'What is the pathophysiology of Type 1 DM?',
    back: 'Autoimmune destruction of pancreatic beta cells → absolute insulin deficiency → glucose cannot enter cells → hyperglycemia. Cells starve despite high blood glucose. Without insulin, body breaks down fat for energy → ketone production → metabolic acidosis (DKA). Onset: usually childhood/adolescence. Requires lifelong insulin therapy.',
    course_code: 'BIOL 4344',
    topic: 'Diabetes Mellitus',
    difficulty: 2,
  },
  {
    id: 'fc-pt07',
    deck_id: 'deck-patho',
    front: 'What is the pathophysiology of Type 2 DM?',
    back: 'Insulin resistance → cells do not respond to insulin properly → pancreas compensates by producing MORE insulin → over time, beta cells "burn out" → relative insulin deficiency → hyperglycemia. Onset: usually adulthood (increasingly in adolescents). Risk factors: obesity, sedentary lifestyle, genetics, age > 45. Initial treatment: lifestyle changes + metformin.',
    course_code: 'BIOL 4344',
    topic: 'Diabetes Mellitus',
    difficulty: 2,
  },
  {
    id: 'fc-pt08',
    deck_id: 'deck-patho',
    front: 'Compare DKA vs. HHS (Hyperosmolar Hyperglycemic Syndrome).',
    back: 'DKA: Type 1 DM (or severely stressed Type 2). BG 250-600 mg/dL. Ketosis + metabolic acidosis (pH < 7.35, bicarb < 18). Kussmaul respirations, fruity breath. Develops rapidly (hours). HHS: Type 2 DM. BG > 600 mg/dL (often > 1000). No significant ketosis (enough insulin to prevent lipolysis, not enough to prevent hyperglycemia). Severe dehydration, altered consciousness. Develops over days-weeks. Higher mortality than DKA.',
    course_code: 'BIOL 4344',
    topic: 'Diabetes Mellitus',
    difficulty: 3,
  },
  {
    id: 'fc-pt09',
    deck_id: 'deck-patho',
    front: 'What is the pathophysiology of pneumonia?',
    back: 'Infectious agents (bacteria, virus, fungus) or aspiration → inflammatory response in alveoli → alveoli fill with fluid, WBCs, and debris (consolidation) → impaired gas exchange → hypoxemia. Consolidation causes: crackles on auscultation, increased tactile fremitus, dullness to percussion, bronchial breath sounds over peripheral lung.',
    course_code: 'BIOL 4344',
    topic: 'Pneumonia',
    difficulty: 2,
  },
  {
    id: 'fc-pt10',
    deck_id: 'deck-patho',
    front: 'What are the classic manifestations of pneumonia?',
    back: 'Fever/chills, productive cough (yellow/green/rust sputum), dyspnea, tachypnea, tachycardia, pleuritic chest pain (sharp, worse with inspiration), crackles on auscultation, decreased breath sounds over affected area. In elderly: may present atypically — confusion/delirium may be the ONLY sign. Elevated WBC, chest X-ray shows infiltrate.',
    course_code: 'BIOL 4344',
    topic: 'Pneumonia',
    difficulty: 2,
  },
  {
    id: 'fc-pt11',
    deck_id: 'deck-patho',
    front: 'What is the pathophysiology of a UTI?',
    back: 'Bacteria (most commonly E. coli, ~80%) ascend through the urethra → colonize the bladder (cystitis). If untreated, may ascend to kidneys (pyelonephritis). Risk factors: female anatomy (short urethra), catheter use, urinary stasis, pregnancy, diabetes. Cystitis signs: dysuria, frequency, urgency, cloudy/foul-smelling urine, suprapubic pain. Pyelonephritis adds: flank pain, fever, CVA tenderness, nausea.',
    course_code: 'BIOL 4344',
    topic: 'UTI',
    difficulty: 2,
  },
  {
    id: 'fc-pt12',
    deck_id: 'deck-patho',
    front: 'What is sepsis and what is the progression from infection to septic shock?',
    back: 'Infection → SIRS (systemic inflammatory response) → Sepsis (infection + organ dysfunction, defined by SOFA score ≥ 2) → Severe sepsis → Septic shock (sepsis + hypotension that persists despite adequate fluid resuscitation + lactate > 2 mmol/L). Pathophysiology: Massive inflammatory response → vasodilation → capillary leak → third-spacing → hypovolemia → organ hypoperfusion → multi-organ failure.',
    course_code: 'BIOL 4344',
    topic: 'Sepsis',
    difficulty: 3,
  },
  {
    id: 'fc-pt13',
    deck_id: 'deck-patho',
    front: 'What is the Sepsis-3 definition and what are early signs nurses should recognize?',
    back: 'Sepsis-3: Life-threatening organ dysfunction caused by dysregulated host response to infection. Screening: qSOFA (quick SOFA) — RR ≥ 22, altered mental status, SBP ≤ 100. ≥ 2 qSOFA = high risk. Early signs: Tachycardia, tachypnea, fever or hypothermia, altered mental status, elevated WBC or very low WBC, elevated lactate > 2 mmol/L. Hour-1 bundle: blood cultures, antibiotics, IV fluids (30 mL/kg crystalloid), vasopressors if needed, lactate measurement.',
    course_code: 'BIOL 4344',
    topic: 'Sepsis',
    difficulty: 3,
  },
  {
    id: 'fc-pt14',
    deck_id: 'deck-patho',
    front: 'What is the pathophysiology of essential hypertension?',
    back: 'Persistent elevation of systemic arterial pressure. 90-95% is primary/essential (no identifiable cause). Pathogenesis involves: increased peripheral vascular resistance, increased cardiac output, RAAS activation, sympathetic nervous system overactivity, endothelial dysfunction, and sodium retention. Called the "silent killer" because it is often asymptomatic until target organ damage occurs (heart, brain, kidneys, eyes).',
    course_code: 'BIOL 4344',
    topic: 'Hypertension',
    difficulty: 2,
  },
  {
    id: 'fc-pt15',
    deck_id: 'deck-patho',
    front: 'What target organ damage results from chronic uncontrolled hypertension?',
    back: 'Heart: Left ventricular hypertrophy → heart failure, coronary artery disease. Brain: Stroke (ischemic or hemorrhagic), vascular dementia. Kidneys: Nephrosclerosis → chronic kidney disease. Eyes: Hypertensive retinopathy (cotton-wool spots, flame hemorrhages, papilledema). Vessels: Atherosclerosis, aortic aneurysm/dissection.',
    course_code: 'BIOL 4344',
    topic: 'Hypertension',
    difficulty: 2,
  },
  {
    id: 'fc-pt16',
    deck_id: 'deck-patho',
    front: 'What is the pathophysiology of acute kidney injury (AKI)?',
    back: 'Rapid decline in kidney function over hours to days. Pre-renal (most common, ~60%): Decreased blood flow to kidneys (hypovolemia, heart failure, shock, sepsis). Intrarenal/Intrinsic: Damage to kidney tissue itself (ATN from ischemia or nephrotoxins, glomerulonephritis). Post-renal: Obstruction of urine outflow (kidney stones, BPH, tumors). Key labs: Rising BUN/creatinine, decreased GFR, oliguria (< 400 mL/day).',
    course_code: 'BIOL 4344',
    topic: 'Renal Failure',
    difficulty: 2,
  },
  {
    id: 'fc-pt17',
    deck_id: 'deck-patho',
    front: 'What are the key electrolyte imbalances in renal failure?',
    back: 'Hyperkalemia (most dangerous — cardiac arrest risk), Hyperphosphatemia (leads to hypocalcemia), Metabolic acidosis (kidneys cannot excrete H+ or reabsorb HCO3-), Hypernatremia or hyponatremia (depending on fluid status), Fluid overload (decreased urine output). Treatment priorities: Treat hyperkalemia first (calcium gluconate, insulin + D50, sodium polystyrene sulfonate).',
    course_code: 'BIOL 4344',
    topic: 'Renal Failure',
    difficulty: 3,
  },
  {
    id: 'fc-pt18',
    deck_id: 'deck-patho',
    front: 'What is the pathophysiology of an ischemic stroke?',
    back: 'Blockage of a cerebral artery (thrombus or embolus) → decreased blood flow to brain tissue → ischemia → if prolonged, infarction (cell death). Penumbra: area of reversible ischemia surrounding the core infarct — salvageable if blood flow is restored quickly. Time is brain: tPA (alteplase) must be given within 3-4.5 hours of symptom onset.',
    course_code: 'BIOL 4344',
    topic: 'Stroke',
    difficulty: 2,
  },
  {
    id: 'fc-pt19',
    deck_id: 'deck-patho',
    front: 'What is the difference between ischemic and hemorrhagic stroke?',
    back: 'Ischemic (87%): Caused by clot (thrombotic or embolic). Treatment: tPA within 3-4.5 hours, thrombectomy within 24 hours (select patients). Hemorrhagic (13%): Caused by ruptured blood vessel (intracerebral hemorrhage or subarachnoid hemorrhage). Often worse headache ("worst headache of my life" for SAH). Treatment: Control BP, manage ICP, possible surgical intervention. tPA is CONTRAINDICATED in hemorrhagic stroke.',
    course_code: 'BIOL 4344',
    topic: 'Stroke',
    difficulty: 3,
  },
  {
    id: 'fc-pt20',
    deck_id: 'deck-patho',
    front: 'What are the classic signs of stroke (BE FAST)?',
    back: 'B = Balance (sudden loss of balance/coordination). E = Eyes (sudden vision changes, blurred or double vision). F = Face (facial drooping, asymmetry — ask to smile). A = Arms (arm weakness/drift — ask to raise both arms). S = Speech (slurred, garbled, or inability to speak). T = Time (note time of symptom onset, call 911 immediately). Additional: sudden severe headache (hemorrhagic), confusion, numbness.',
    course_code: 'BIOL 4344',
    topic: 'Stroke',
    difficulty: 1,
  },
  {
    id: 'fc-pt21',
    deck_id: 'deck-patho',
    front: 'What is the RAAS system and how does it affect blood pressure?',
    back: 'Renin-Angiotensin-Aldosterone System: Decreased renal perfusion → kidneys release renin → converts angiotensinogen to angiotensin I → ACE (in lungs) converts it to angiotensin II → potent vasoconstrictor + stimulates aldosterone release from adrenal cortex → aldosterone causes Na+ and water retention → increased blood volume and BP. Drugs targeting RAAS: ACE inhibitors (block ACE), ARBs (block AT1 receptor), aldosterone antagonists (spironolactone).',
    course_code: 'BIOL 4344',
    topic: 'Hypertension',
    difficulty: 3,
  },
  {
    id: 'fc-pt22',
    deck_id: 'deck-patho',
    front: 'What are the microvascular and macrovascular complications of diabetes mellitus?',
    back: 'Microvascular: Retinopathy (leading cause of blindness), Nephropathy (leading cause of ESRD), Neuropathy (peripheral — numbness/tingling feet, autonomic — gastroparesis, orthostatic hypotension). Macrovascular: Coronary artery disease, Peripheral artery disease, Cerebrovascular disease (stroke). All caused by chronic hyperglycemia damaging blood vessel endothelium. HbA1c goal < 7% reduces complications.',
    course_code: 'BIOL 4344',
    topic: 'Diabetes Mellitus',
    difficulty: 2,
  },
  {
    id: 'fc-pt23',
    deck_id: 'deck-patho',
    front: 'What is the pathophysiology of asthma?',
    back: 'Chronic inflammatory airway disease with three components: 1) Bronchoconstriction (smooth muscle spasm), 2) Airway inflammation (edema, mucus hypersecretion), 3) Airway hyperresponsiveness to triggers (allergens, exercise, cold air, infection). Results in: reversible airway obstruction, wheezing (especially on expiration), dyspnea, chest tightness, cough. Key difference from COPD: asthma is REVERSIBLE.',
    course_code: 'BIOL 4344',
    topic: 'Respiratory',
    difficulty: 2,
  },
  {
    id: 'fc-pt24',
    deck_id: 'deck-patho',
    front: 'What is status asthmaticus?',
    back: 'A severe, life-threatening asthma attack that does NOT respond to standard bronchodilator therapy. Medical emergency. Signs: severe wheezing that may progress to "silent chest" (air movement too poor to generate wheeze — ominous sign), severe dyspnea, accessory muscle use, cyanosis, altered LOC. Treatment: continuous nebulized albuterol, IV corticosteroids, IV magnesium sulfate, possible intubation.',
    course_code: 'BIOL 4344',
    topic: 'Respiratory',
    difficulty: 3,
  },
  {
    id: 'fc-pt25',
    deck_id: 'deck-patho',
    front: 'How does chronic kidney disease (CKD) differ from acute kidney injury (AKI)?',
    back: 'AKI: Sudden onset (hours-days), often reversible, caused by pre-renal/intrarenal/post-renal factors. CKD: Progressive, irreversible loss of kidney function over months-years. Defined as GFR < 60 mL/min/1.73m2 for ≥ 3 months. Stages 1-5 based on GFR. Stage 5 (GFR < 15) = ESRD, requires dialysis or transplant. Causes: diabetes (#1), hypertension (#2).',
    course_code: 'BIOL 4344',
    topic: 'Renal Failure',
    difficulty: 2,
  },
  {
    id: 'fc-pt26',
    deck_id: 'deck-patho',
    front: 'What is the pathophysiology of pulmonary embolism (PE)?',
    back: 'A blood clot (usually from DVT in legs) breaks free → travels through venous system → right heart → lodges in pulmonary artery → blocks blood flow to lungs → V/Q mismatch → hypoxemia. Large PE can cause right heart failure and cardiac arrest. Signs: sudden dyspnea, tachycardia, tachypnea, pleuritic chest pain, anxiety, hemoptysis, decreased O2 sat. Risk factors: Virchow triad (stasis, endothelial injury, hypercoagulability).',
    course_code: 'BIOL 4344',
    topic: 'Pulmonary',
    difficulty: 3,
  },
  {
    id: 'fc-pt27',
    deck_id: 'deck-patho',
    front: 'What is the inflammatory response and its cardinal signs?',
    back: 'Tissue injury → mast cells release histamine → vasodilation and increased capillary permeability → plasma and WBCs flood tissue. Cardinal signs: Rubor (redness), Calor (heat), Tumor (swelling), Dolor (pain), and Functio laesa (loss of function). Acute inflammation is beneficial (defense/healing). Chronic inflammation = tissue damage (autoimmune diseases, atherosclerosis).',
    course_code: 'BIOL 4344',
    topic: 'Inflammation',
    difficulty: 1,
  },
  {
    id: 'fc-pt28',
    deck_id: 'deck-patho',
    front: 'What is the oxyhemoglobin dissociation curve and what shifts it right?',
    back: 'Right shift = hemoglobin releases O2 more easily to tissues (decreased O2 affinity). Causes: increased temperature (fever), increased CO2, increased 2,3-DPG, decreased pH (acidosis). Think: exercising muscle is hot, acidotic, high CO2 — it needs MORE O2 delivered. Left shift = hemoglobin holds onto O2 more tightly (opposite conditions). Mnemonic for right shift: "CADET, face Right" — CO2, Acidosis, 2,3-DPG, Exercise, Temperature.',
    course_code: 'BIOL 4344',
    topic: 'Respiratory Physiology',
    difficulty: 3,
  },
  {
    id: 'fc-pt29',
    deck_id: 'deck-patho',
    front: 'What is the difference between metabolic acidosis and respiratory acidosis?',
    back: 'Metabolic acidosis: pH < 7.35, HCO3- < 22 mEq/L. Causes: DKA, lactic acidosis, renal failure, diarrhea. Compensation: lungs blow off CO2 (Kussmaul respirations). Respiratory acidosis: pH < 7.35, PaCO2 > 45 mmHg. Causes: COPD, respiratory depression (opioids), pneumonia. Compensation: kidneys retain HCO3-. Remember: "ROME" — Respiratory = Opposite (pH and CO2 move opposite), Metabolic = Equal (pH and HCO3- move same direction).',
    course_code: 'BIOL 4344',
    topic: 'Acid-Base Balance',
    difficulty: 3,
  },
  {
    id: 'fc-pt30',
    deck_id: 'deck-patho',
    front: 'What is the pathophysiology of atherosclerosis?',
    back: 'Endothelial injury (from HTN, smoking, diabetes, hyperlipidemia) → lipid accumulation in vessel wall → macrophages engulf lipids (foam cells) → fatty streak forms → smooth muscle proliferation and collagen deposition → fibrous plaque → plaque narrows the vessel lumen → ischemia. If plaque ruptures → thrombus forms → acute occlusion → MI or ischemic stroke. Prevention: statins, BP control, smoking cessation, diabetes management, exercise.',
    course_code: 'BIOL 4344',
    topic: 'Cardiovascular',
    difficulty: 2,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DECK 5 — NCLEX Priority Setting (20 cards)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'fc-n01',
    deck_id: 'deck-nclex',
    front: 'What is the ABC priority framework?',
    back: 'Airway > Breathing > Circulation. Always address airway FIRST (obstruction, edema, secretions), then breathing (oxygenation, ventilation), then circulation (bleeding, perfusion, cardiac output). Exception: In cardiac arrest, use CAB (Compressions, Airway, Breathing) per AHA guidelines.',
    course_code: 'NURS 3193',
    topic: 'Priority Setting',
    difficulty: 1,
  },
  {
    id: 'fc-n02',
    deck_id: 'deck-nclex',
    front: 'A nurse is caring for 4 patients. Which should be assessed FIRST? A) Post-op patient requesting pain medication. B) Patient with COPD with O2 sat of 86%. C) Patient with a blood glucose of 250 mg/dL. D) Patient with a new onset headache.',
    back: 'B) COPD patient with O2 sat 86%. While 88-92% is the target for COPD, 86% is BELOW the acceptable range — this is a breathing/oxygenation issue (ABC priority). A) Pain is important but not life-threatening. C) BG 250 is elevated but not critical. D) Headache needs assessment but is not emergent based on the info given.',
    course_code: 'NURS 3193',
    topic: 'Priority Setting',
    difficulty: 2,
  },
  {
    id: 'fc-n03',
    deck_id: 'deck-nclex',
    front: 'How does Maslow\'s hierarchy help with NCLEX prioritization?',
    back: 'Address LOWER-level needs before higher-level needs. Order: 1) Physiological (oxygenation, fluids, nutrition, elimination, pain) → 2) Safety (fall prevention, infection control, medication errors) → 3) Love/Belonging → 4) Esteem → 5) Self-actualization. On NCLEX: a physical need always takes priority over a psychosocial need, UNLESS the physical need is already stable/addressed.',
    course_code: 'NURS 3193',
    topic: 'Priority Setting',
    difficulty: 1,
  },
  {
    id: 'fc-n04',
    deck_id: 'deck-nclex',
    front: 'What is the "acute vs. chronic" rule for prioritization?',
    back: 'NEW-onset or ACUTE changes take priority over chronic, stable conditions. A patient with a new temperature of 101.5°F takes priority over a patient with a chronic wound that looks the same as yesterday. "What is different? What is unexpected? What is deteriorating?" — these patients come first.',
    course_code: 'NURS 3193',
    topic: 'Priority Setting',
    difficulty: 2,
  },
  {
    id: 'fc-n05',
    deck_id: 'deck-nclex',
    front: 'Which tasks can a nurse delegate to a UAP (unlicensed assistive personnel)?',
    back: 'UAP can: Vital signs (stable patients), bathing, ambulation, feeding, I&O measurement, daily weights, blood glucose monitoring (finger stick), CPR, turning/repositioning, transport. UAP CANNOT: Initial assessment, teaching, evaluation, administer medications, interpret data, make clinical decisions, perform sterile procedures, receive provider orders.',
    hint: 'Remember ATE: Assessment, Teaching, Evaluation = NEVER delegated.',
    course_code: 'NURS 3193',
    topic: 'Delegation',
    difficulty: 1,
  },
  {
    id: 'fc-n06',
    deck_id: 'deck-nclex',
    front: 'A charge nurse is making assignments. Which patient is MOST appropriate to assign to an LPN/LVN?',
    back: 'Assign the LPN/LVN a STABLE patient with PREDICTABLE outcomes. LPNs can: collect data (not initial assessment), give PO/IM/Sub-Q medications, perform dressing changes, maintain existing IVs, trach suctioning, catheter care. LPNs should NOT be assigned: new admissions (requires initial assessment), unstable patients, blood transfusions, IV push medications, patient teaching, or patients requiring complex clinical judgment.',
    course_code: 'NURS 3193',
    topic: 'Delegation',
    difficulty: 2,
  },
  {
    id: 'fc-n07',
    deck_id: 'deck-nclex',
    front: '"Which patient should the nurse see FIRST?" — what is the strategy for these questions?',
    back: 'Strategy: 1) Apply ABCs — which patient has an airway/breathing/circulation threat? 2) Identify the UNEXPECTED finding (abnormal vital signs, new symptoms, acute change). 3) Eliminate stable/expected findings. 4) Think: "Who will DIE or deteriorate if I do not act NOW?" For post-op patients: new-onset tachycardia + hypotension = bleeding until proven otherwise → see first.',
    course_code: 'NURS 3193',
    topic: 'Priority Setting',
    difficulty: 2,
  },
  {
    id: 'fc-n08',
    deck_id: 'deck-nclex',
    front: 'A nurse is caring for 4 patients. Which should be assessed FIRST? A) Patient 2 days post-hip replacement with pain 5/10. B) Patient with asthma who has new-onset wheezing. C) Patient with diabetes who has a blood glucose of 180 mg/dL. D) Patient with pneumonia whose temperature is 99.8°F.',
    back: 'B) Asthma patient with new-onset wheezing. This is an AIRWAY/BREATHING priority and represents an ACUTE change. A) Expected post-op pain, manageable. C) BG 180 is slightly elevated but not critical. D) Low-grade fever is expected with pneumonia. New wheezing suggests bronchospasm that could worsen rapidly.',
    course_code: 'NURS 3193',
    topic: 'Priority Setting',
    difficulty: 2,
  },
  {
    id: 'fc-n09',
    deck_id: 'deck-nclex',
    front: 'When should a nurse question a provider\'s order instead of implementing it?',
    back: 'Question when: Order is unclear/incomplete, dose is outside normal range, drug is contraindicated for this patient (allergies, labs, condition), order conflicts with another order, nursing judgment indicates potential harm. Steps: Clarify with the prescriber. If unresolved, go up the chain of command (charge nurse → supervisor → provider\'s superior). DOCUMENT everything. Patient safety always takes priority over hierarchy.',
    course_code: 'NURS 3193',
    topic: 'Patient Safety',
    difficulty: 2,
  },
  {
    id: 'fc-n10',
    deck_id: 'deck-nclex',
    front: 'What is the "safety vs. comfort" rule on NCLEX?',
    back: 'Safety ALWAYS takes priority over comfort. Example: A patient in restraints requesting removal — assess the reason for restraints and safety risk before removing. A patient requesting to get up to use the bathroom who is at high fall risk — assist them, do not let them go alone. However, do not ignore comfort — address it AFTER safety is ensured.',
    course_code: 'NURS 3193',
    topic: 'Priority Setting',
    difficulty: 2,
  },
  {
    id: 'fc-n11',
    deck_id: 'deck-nclex',
    front: 'What is the priority nursing action when a patient is found unresponsive?',
    back: 'Check responsiveness (tap and shout). Call for help / activate code blue. Check for breathing and pulse simultaneously (no more than 10 seconds). If no pulse: Begin CPR (CAB: 30 compressions : 2 breaths). Attach AED as soon as available. Push hard (2+ inches), push fast (100-120/min), allow full recoil.',
    course_code: 'NURS 3193',
    topic: 'Emergency Response',
    difficulty: 1,
  },
  {
    id: 'fc-n12',
    deck_id: 'deck-nclex',
    front: 'What should a nurse do when receiving a critical lab value?',
    back: 'Critical (panic) values require IMMEDIATE notification of the provider. Examples: K+ < 3.0 or > 6.0 mEq/L, Na+ < 120 or > 160 mEq/L, glucose < 50 or > 400 mg/dL, Hgb < 7 g/dL, platelets < 50,000. Steps: Verify the result (recheck if possible), notify the provider immediately using SBAR, document the notification (time, who was notified, orders received), implement orders.',
    course_code: 'NURS 3193',
    topic: 'Patient Safety',
    difficulty: 2,
  },
  {
    id: 'fc-n13',
    deck_id: 'deck-nclex',
    front: 'A patient who is 1 day post-op has a heart rate of 110 bpm and blood pressure of 88/60 mmHg. What is the priority nursing action?',
    back: 'Assess for internal hemorrhage — these are classic signs of hypovolemic shock (tachycardia compensates for blood loss, hypotension occurs as volume depletes). Priority actions: Assess the surgical site and drains, check Hgb/Hct, keep patient flat with legs elevated (unless contraindicated), increase IV fluid rate per protocol, and NOTIFY the provider immediately. Do NOT medicate for pain until you rule out hemorrhage.',
    course_code: 'NURS 3193',
    topic: 'Priority Setting',
    difficulty: 3,
  },
  {
    id: 'fc-n14',
    deck_id: 'deck-nclex',
    front: 'What does the NCLEX mean by "therapeutic communication"?',
    back: 'Use open-ended questions ("Tell me more about your pain"), reflection ("It sounds like you are worried"), empathy, active listening, and silence. AVOID: "Why" questions (makes patient defensive), giving personal opinions, false reassurance ("Everything will be fine"), changing the subject, giving approval/disapproval. On NCLEX, the answer that explores the patient\'s feelings is usually correct.',
    course_code: 'NURS 3193',
    topic: 'Communication',
    difficulty: 1,
  },
  {
    id: 'fc-n15',
    deck_id: 'deck-nclex',
    front: 'A patient with a history of falls wants to go to the bathroom independently at night. What does the nurse do?',
    back: 'Balance safety AND autonomy. Do NOT restrain or tell the patient they cannot go. Instead: Put bed in lowest position, ensure call light is in reach, provide non-skid socks, clear pathway, keep nightlight on, offer to assist, set up a bedside commode if appropriate, activate bed alarm. Patient has the RIGHT to refuse help — document education and refusal. Safety is priority, but respect autonomy.',
    course_code: 'NURS 3193',
    topic: 'Priority Setting',
    difficulty: 3,
  },
  {
    id: 'fc-n16',
    deck_id: 'deck-nclex',
    front: 'When triaging patients in the ED, which patient should be seen FIRST? A) 45-year-old with chest pain radiating to the left arm. B) 8-year-old with a forearm deformity and pain. C) 70-year-old with a UTI and fever of 100.4°F. D) 30-year-old with a laceration requiring stitches.',
    back: 'A) 45-year-old with chest pain radiating to left arm. This is a potential MI — life-threatening emergency requiring immediate intervention. B) Likely fracture — urgent but not immediately life-threatening. C) UTI with low-grade fever — needs treatment but can wait. D) Laceration — non-emergent.',
    course_code: 'NURS 3193',
    topic: 'Priority Setting',
    difficulty: 2,
  },
  {
    id: 'fc-n17',
    deck_id: 'deck-nclex',
    front: 'What is the "expected vs. unexpected" rule for NCLEX?',
    back: 'Expected findings for a condition do not need IMMEDIATE intervention — they need continued monitoring and scheduled treatment. UNEXPECTED findings require priority assessment and provider notification. Example: A patient with pneumonia who has a fever of 100.2°F and productive cough = EXPECTED. Same patient who suddenly becomes confused and tachypneic = UNEXPECTED (possible sepsis) → see first.',
    course_code: 'NURS 3193',
    topic: 'Priority Setting',
    difficulty: 2,
  },
  {
    id: 'fc-n18',
    deck_id: 'deck-nclex',
    front: 'Which patient can be safely discharged first from the post-anesthesia care unit (PACU)?',
    back: 'The patient who meets discharge criteria: Aldrete score ≥ 9 (assesses activity, respiration, circulation, consciousness, O2 sat). Must have: stable vital signs for at least 30 minutes, alert and oriented, adequate pain control, no active bleeding, no nausea/vomiting, able to swallow, intact gag reflex. A patient still drowsy with O2 sat of 92% should NOT be discharged.',
    course_code: 'NURS 3193',
    topic: 'Priority Setting',
    difficulty: 3,
  },
  {
    id: 'fc-n19',
    deck_id: 'deck-nclex',
    front: 'When is it appropriate to call a Rapid Response Team (RRT)?',
    back: 'When a patient shows signs of clinical deterioration but has NOT yet had a cardiac/respiratory arrest. Triggers include: acute change in HR (< 40 or > 130), RR (< 8 or > 28), SBP (< 90), O2 sat (< 90% on O2), acute change in mental status, new-onset chest pain, urine output < 50 mL in 4 hours, or nurse\'s clinical judgment that "something is wrong." Early activation saves lives — do not wait until the patient codes.',
    course_code: 'NURS 3193',
    topic: 'Patient Safety',
    difficulty: 2,
  },
  {
    id: 'fc-n20',
    deck_id: 'deck-nclex',
    front: 'A nurse must give medications to 4 patients at 0900. Which medication should be given FIRST? A) Metoprolol 50 mg PO. B) Insulin lispro 6 units Sub-Q. C) Atorvastatin 40 mg PO. D) Amlodipine 5 mg PO.',
    back: 'B) Insulin lispro. Rapid-acting insulin must be given within 15 minutes of the meal to match glucose absorption. Timing is critical for blood glucose control and preventing hyper/hypoglycemia. The other medications (metoprolol, atorvastatin, amlodipine) do not have the same time-sensitive requirement for effectiveness.',
    course_code: 'NURS 3193',
    topic: 'Priority Setting',
    difficulty: 2,
  },
];
